--- 
abstract: Automatically generate code upon require or use
author: 
  - Andrew Sterling Hanenkamp C<< <hanenkamp@cpan.org> >>
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Class-AutoGenerate
no_index: 
  directory: 
    - inc
    - t
version: 0.01
